#!/usr/bin/env bash

set -e
cd $(dirname $0)

echo "-> Creating dotfile links..."

ln -sfv $PWD/bash_profile	$HOME/.bash_profile
ln -sfv $PWD/bashrc			$HOME/.bashrc
ln -sfv $PWD/gitconfig		$HOME/.gitconfig
ln -sfv $PWD/inputrc		$HOME/.inputrc
ln -sfv $PWD/vimrc			$HOME/.vimrc
ln -sfv $PWD/xinitrc		$HOME/.xinitrc
ln -sfv $PWD/XKBkeymap		$HOME/.XKBkeymap
#ln -sfv $PWD/Xmodmap		$HOME/.Xmodmap

mkdir -pv $HOME/.config/htop
ln -sfv $PWD/htoprc			$HOME/.config/htop/htoprc

mkdir -pv $HOME/.gnupg
chmod -v 700 $HOME/.gnupg
ln -sfv	$PWD/gpg.conf		$HOME/.gnupg/gpg.conf
chmod -v 600 $HOME/.gnupg/gpg.conf

echo "-> Done!"
